const categoryTypes = {
    ADD_CATEGORY_PENDING: 'ADD_CATEGORY_PENDING',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_ERROR: 'ADD_CATEGORY_ERROR',

    FETCH_DEFAULT_CATEGORIES_PENDING: 'FETCH_DEFAULT_CATEGORIES_PENDING',
    FETCH_DEFAULT_CATEGORIES_SUCCESS: 'FETCH_DEFAULT_CATEGORIES_SUCCESS',
    FETCH_DEFAULT_CATEGORIES_ERROR: 'FETCH_DEFAULT_CATEGORIES_ERROR',
}

export default categoryTypes