const questionTypes = {
    ADD_QUESTION_PENDING: 'ADD_QUESTION_PENDING',
    ADD_QUESTION_SUCCESS: 'ADD_QUESTION_SUCCESS',
    ADD_QUESTION_ERROR: 'ADD_QUESTION_ERROR',

    FETCH_DEFAULT_QUESTIONS_PENDING: 'FETCH_DEFAULT_QUESTIONS_PENDING',
    FETCH_DEFAULT_QUESTIONS_SUCCESS: 'FETCH_DEFAULT_QUESTIONS_SUCCESS',
    FETCH_DEFAULT_QUESTIONS_ERROR: 'FETCH_DEFAULT_QUESTIONS_ERROR',
}

export default questionTypes