const quizTypes = {

    CREATE_QUIZ_START: 'CREATE_QUIZ_START',
    CREATE_QUIZ_SUCCESS: 'CREATE_QUIZ_SUCCESS',
    CREATE_QUIZ_ERROR: 'CREATE_QUIZ_ERROR',

    SET_QUIZ_CATEGORIES_START: 'SET_QUIZ_CATEGORIES_START',
    SET_QUIZ_CATEGORIES_STUCCESS: 'SET_QUIZ_CATEGORIES_SUCCESS',
    SET_QUIZ_CATEGORIES_ERROR: 'SET_QUIZ_CATEGORIES_ERROR',

    SET_QUIZ_QUESTIONS_START: 'SET_QUIZ_QUESTIONS_START',
    SET_QUIZ_QUESTIONS_SUCCESS: 'SET_QUIZ_QUESTIONS_SUCCESS',
    SET_QUIZ_QUESTIONS_ERROR: 'SET_QUIZ_QUESTIONS_ERROR',

    SET_QUIZ_QUESTION_START: 'SET_QUIZ_QUESTION_START',
    SET_QUIZ_QUESTION_SUCCESS: 'SET_QUIZ_QUESTION_SUCCESS',
    SET_QUIZ_QUESTION_ERROR: 'SET_QUIZ_QUESTION_ERROR',

    FETCH_USER_QUIZZES_START: 'FETCH_USER_QUIZZES_START',
    FETCH_USER_QUIZZES_SUCCESS: 'FETCH_USER_QUIZZES_SUCCESS',
    FETCH_USER_QUIZZES_ERROR: 'FETCH_USER_QUIZZES_ERROR',

    SET_EDIT_QUIZ_STATE: 'SET_EDIT_QUIZ_STATE'

}

export const quizStates = {
    EDIT_TITLE: 'EDIT_TITLE',
    EDIT_CATEGORIES: 'EDIT_CATEGORIES',
    EDIT_QUESTIONS: 'EDIT_QUESTIONS'
}

export default quizTypes
